name: Java CI with Gradle

# 동작 조건 설정 : main 브랜치에 push 혹은 pull request가 발생할 경우 동작한다.
on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 1. Java 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      ## create application-database.yaml
      - name: create application.properties file
        run: |
          mkdir ./src/main/resources
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> src/main/resources/application.yml

      ## create firebase-service-key.json
      - name: create firebase_service_key.json file
        run: |
          mkdir ./src/main/resources/firebase
          touch ./src/main/resources/firebase/firebase_service_key.json
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" > src/main/resources/firebase/firebase_service_key.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # 2. Spring Boot 애플리케이션 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      # 3. Docker 이미지 빌드
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jangburich2 .

      # 4. DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5. Docker Hub 이미지 푸시
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/jangburich2

  deploy-using-docker-compose:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
      # Docker Compose 파일을 EC2로 복사
      - name: Copy docker-compose.yml to EC2
        run: scp /Users/rookie/IdeaProjects/2024_DANPOONG_TEAM_5_BE/docker-compose.yml ec2-user@3.36.98.64:~/app/docker-compose.yml

      # 최신 Docker 이미지 Pull
      - name: Pull the latest Docker image on EC2
        run: ssh ec2-user@3.36.98.64 "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jangburich2"

      # Docker Compose 실행
      - name: Start services with docker-compose
        run: ssh ec2-user@3.36.98.64 "cd ~/app && docker-compose up -d --build"

      # Docker 시스템 청소
      - name: Cleanup old Docker images
        run: ssh ec2-user@3.36.98.64 "docker system prune -f"